timApp/document/course/routes.py
"""
Contains course related routes.
"""

from flask import Blueprint
from sqlalchemy.orm import joinedload

from timApp.auth.sessioninfo import get_current_user_object
from timApp.bookmark.bookmarks import Bookmarks
from timApp.document.docentry import DocEntry, get_documents
from timApp.item.block import Block
from timApp.util.flask.responsehelper import json_response

course_blueprint = Blueprint('course',
                             __name__,
                             url_prefix='/courses')


@course_blueprint.route("/settings")
def get_course_settings():
    """
    Get course settings from the designated settings document.
    :return: Settings from the course settings.
    """
    d = DocEntry.find_by_path("settings/courses")
    if not d:
        return json_response({})
    return json_response(d.document.get_settings().get_dict().values)


@course_blueprint.route("/documents/<string:foldername>")
def get_documents_from_bookmark_folder(foldername):
    """
    Gets documents and their tags based on a bookmark folder name.
    :param foldername:
    :return:
    """
    folder = None
    paths = []
    bookmark_folders = Bookmarks(get_current_user_object())
    for bookmark_folder in bookmark_folders.as_dict():
        if bookmark_folder['name'] == foldername:
            folder = bookmark_folder
    if folder:
        for bookmark in folder['items']:
            paths.append(bookmark['link'].replace("/view/", "", 1))
    else:
        return json_response([])
    docs = get_documents(filter_user=get_current_user_object(),
                         custom_filter=DocEntry.name.in_(paths),
                         query_options=joinedload(DocEntry._block).joinedload(Block.tags))
    return json_response(docs)

timApp/document/routes.py
import attr
from flask import Response, abort, request, Blueprint
from marshmallow import Schema, fields, post_load
from webargs.flaskparser import use_args

from timApp.auth.accesshelper import get_doc_or_abort, verify_edit_access, can_see_par_source
from timApp.auth.sessioninfo import get_current_user_object
from timApp.document.docparagraph import DocParagraph
from timApp.document.document import Document
from timApp.document.documentversion import DocumentVersion
from timApp.timdb.exceptions import TimDbException
from timApp.util.flask.requesthelper import get_option
from timApp.util.flask.responsehelper import json_response

doc_bp = Blueprint('document',
                   __name__,
                   url_prefix='')


@doc_bp.route('/download/<int:doc_id>')
def download_document(doc_id):
    d = get_doc_or_abort(doc_id)
    verify_edit_access(d)
    return return_doc_content(d.document)


def return_doc_content(d: Document):
    use_raw = get_option(request, 'format', 'md') == 'json'
    if use_raw:
        return json_response(d.export_raw_data())
    else:
        return Response(d.export_markdown(), mimetype="text/plain")


@doc_bp.route('/download/<int:doc_id>/<int:major>/<int:minor>')
def download_document_version(doc_id, major, minor):
    d = get_doc_or_abort(doc_id)
    verify_edit_access(d)
    doc = DocumentVersion(doc_id, (major, minor))
    if not doc.exists():
        abort(404, "This document version does not exist.")
    return return_doc_content(doc)


@doc_bp.route('/diff/<int:doc_id>/<int:major1>/<int:minor1>/<int:major2>/<int:minor2>')
def diff_document(doc_id, major1, minor1, major2, minor2):
    d = get_doc_or_abort(doc_id)
    verify_edit_access(d)
    doc1 = DocumentVersion(doc_id, (major1, minor1))
    doc2 = DocumentVersion(doc_id, (major2, minor2))
    if not doc1.exists():
        abort(404, f"The document version {(major1, minor1)} does not exist.")
    if not doc2.exists():
        abort(404, f"The document version {(major2, minor2)} does not exist.")
    return Response(DocumentVersion.get_diff(doc1, doc2), mimetype="text/html")


@attr.s(auto_attribs=True)
class GetBlockModel:
    doc_id: int = None
    par_id: str = None
    area_start: str = None
    area_end: str = None
    use_exported: bool = True
    par_hash: str = None


class GetBlockSchema(Schema):
    doc_id = fields.Int()
    par_id = fields.Str()
    area_start = fields.Str()
    area_end = fields.Str()
    use_exported = fields.Bool(missing=True)
    par_hash = fields.Str(missing=None)

    @post_load
    def make_obj(self, data):
        # noinspection PyArgumentList
        return GetBlockModel(**data)


@doc_bp.route("/getBlock/<int:doc_id>/<par_id>")
def get_block(doc_id, par_id):
    return get_block_2(GetBlockModel(
        area_end=request.args.get('area_end'),
        area_start=request.args.get('area_start'),
        doc_id=doc_id,
        par_id=par_id,
    ))


@doc_bp.route("/getBlock")
@use_args(GetBlockSchema(strict=True))
def get_block_schema(args: GetBlockModel):
    return get_block_2(args)


def get_block_2(args: GetBlockModel):
    d = get_doc_or_abort(args.doc_id)
    area_start = args.area_start
    area_end = args.area_end
    if area_start and area_end:
        verify_edit_access(d)
        try:
            section = d.document.export_section(area_start, area_end)
        except TimDbException as e:
            return abort(404, 'Area not found. It may have been deleted.')
        return json_response({"text": section})
    else:
        try:
            p = d.document.get_paragraph(args.par_id)
            if not can_see_par_source(get_current_user_object(), p):
                abort(403)
            if args.par_hash:
                par = DocParagraph.get(d.document, args.par_id, args.par_hash or p.get_hash())
            else:
                par = p
        except TimDbException as e:
            return abort(404, 'Paragraph not found. It may have been deleted.')
        if args.use_exported:
            return json_response({"text": par.get_exported_markdown()})
        else:
            return json_response({"text": par.get_markdown()})

timApp/item/routes.py
"""Routes for document view."""
import time
import traceback
from typing import Tuple, Union, Optional, List

from flask import Blueprint, render_template
from flask import abort
from flask import current_app
from flask import flash
from flask import redirect
from flask import request
from flask import session

from timApp.answer.answers import add_missing_users_from_group
from timApp.auth.accesshelper import verify_view_access, verify_teacher_access, verify_seeanswers_access, \
    get_rights, has_edit_access, get_doc_or_abort, verify_manage_access
from timApp.item.block import BlockType
from timApp.item.blockrelevance import BlockRelevance
from timApp.document.create_item import create_or_copy_item, create_citation_doc
from timApp.document.post_process import post_process_pars, \
    hide_names_in_teacher
from timApp.folder.folder_view import try_return_folder
from timApp.item.item import Item
from timApp.item.validation import has_special_chars
from timApp.tim_app import app
from timApp.timdb.dbaccess import get_timdb
from timApp.document.docparagraph import DocParagraph
from timApp.document.docsettings import DocSettings
from timApp.document.document import get_index_from_html_list, dereference_pars, Document
from timApp.document.preloadoption import PreloadOption
from timApp.markdown.htmlSanitize import sanitize_html
from timApp.util.logger import log_error
from timApp.markdown.markdownconverter import create_environment
from timApp.plugin.pluginControl import find_task_ids, get_all_reqs
from timApp.timdb.sqa import db
from timApp.util.flask.requesthelper import get_option, verify_json_params
from timApp.util.flask.responsehelper import json_response, ok_response
from timApp.auth.sessioninfo import get_current_user_object, logged_in, current_user_in_lecture, \
    get_user_settings, save_last_page
from timApp.document.docinfo import DocInfo
from timApp.timdb.exceptions import TimDbException, PreambleException
from timApp.document.docentry import DocEntry, get_documents
from timApp.folder.folder import Folder
from timApp.user.user import User
from timApp.user.usergroup import UserGroup
from timApp.util.timtiming import taketime
from timApp.util.utils import remove_path_special_chars, Range
from timApp.util.utils import get_error_message

DEFAULT_RELEVANCE = 10

view_page = Blueprint('view_page',
                      __name__,
                      url_prefix='')


def get_partial_document(doc: Document, view_range: Range) -> List[DocParagraph]:
    i = 0
    pars = []
    for par in doc:
        if i >= view_range[1]:
            break
        if i >= view_range[0]:
            pars.append(par)
        i += 1
    return pars


def get_document(doc_info: DocInfo, view_range: Optional[Range] = None) -> Tuple[Document, List[DocParagraph]]:
    # Separated into 2 functions for optimization
    # (don't cache partial documents and don't check ranges in the loop for whole ones)
    doc = doc_info.document
    doc.preload_option = PreloadOption.all
    return doc, (doc.get_paragraphs() if view_range is None else get_partial_document(doc, view_range))


@view_page.route("/show_slide/<path:doc_name>")
def show_slide(doc_name):
    html = view(doc_name, 'show_slide.html')
    return html


@view_page.route("/view/<path:doc_name>")
@view_page.route("/view_html/<path:doc_name>")
@view_page.route("/doc/<path:doc_name>")
def view_document(doc_name):
    taketime("route view begin")
    ret = view(doc_name, 'view_html.html')
    taketime("route view end")
    return ret


@view_page.route("/teacher/<path:doc_name>")
def teacher_view(doc_name):
    usergroup = request.args.get('group')
    return view(doc_name, 'view_html.html', usergroup=usergroup, route="teacher")


@view_page.route("/velp/<path:doc_name>")
def velp_view(doc_name):
    usergroup = request.args.get('group')
    return view(doc_name, 'view_html.html', usergroup=usergroup, route="velp")


@view_page.route("/answers/<path:doc_name>")
def see_answers_view(doc_name):
    usergroup = request.args.get('group')
    return view(doc_name, 'view_html.html', usergroup=usergroup, route="answers")


@view_page.route("/lecture/<path:doc_name>")
def lecture_view(doc_name):
    return view(doc_name, 'view_html.html', route="lecture")


@view_page.route("/slide/<path:doc_name>")
def slide_document(doc_name):
    html = view(doc_name, 'view_html.html', route="slide")
    return html


@view_page.route("/par_info/<int:doc_id>/<par_id>")
def par_info(doc_id, par_id):
    info = {}

    doc = get_doc_or_abort(doc_id)
    info['doc_name'] = doc.title

    group: UserGroup = doc.owner
    users = group.users.all()
    if len(users) == 1:
        info['doc_author'] = f'{users[0].real_name} ({group.name})'
    else:
        info['doc_author'] = group.name

    par_name = doc.document.get_closest_paragraph_title(par_id)
    if par_name is not None:
        info['par_name'] = par_name

    return json_response(info)


@view_page.route("/getItems")
def items_route():
    folderpath = request.args.get('folder', '')
    f = Folder.find_by_path(folderpath)
    if not f.is_root():
        verify_view_access(f)
    return json_response(get_items(folderpath))


@view_page.route("/view")
def index_page():
    save_last_page()
    in_lecture = current_user_in_lecture()
    return render_template('index.html',
                           items=get_items(''),
                           in_lecture=in_lecture,
                           item=Folder.get_root())


def parse_range(start_index: Union[int, str, None], end_index: Union[int, str, None]) -> Optional[Range]:
    if start_index is None and end_index is None:
        return None
    return int(start_index), int(end_index)


debug_time = time.time()


def show_time(s):
    global debug_time
    now = time.time()
    print(s, now - debug_time)
    debug_time = now


def get_module_ids(js_paths: List[str]):
    for jsfile in js_paths:
        yield jsfile.lstrip('/').rstrip('.js')


def view(item_path, template_name, usergroup=None, route="view"):
    taketime("view begin", zero=True)
    if has_special_chars(item_path):
        return redirect(remove_path_special_chars(request.path) + '?' + request.query_string.decode('utf8'))

    save_last_page()

    doc_info = DocEntry.find_by_path(item_path, fallback_to_id=True)

    if doc_info is None:
        return try_return_folder(item_path)

    doc_id = doc_info.id
    edit_mode = request.args.get('edit', None) if has_edit_access(doc_info) else None
    create_environment("%%")  # TODO get macroinf

    hide_names = get_option(request, 'hide_names', None, cast=bool)
    if hide_names is not None:
        session['hide_names'] = hide_names
    if route == 'teacher':
        if not verify_teacher_access(doc_info, require=False, check_duration=True):
            if verify_view_access(doc_info):
                flash("Did someone give you a wrong link? Showing normal view instead of teacher view.")
                return redirect(f'/view/{item_path}')

    if route == 'answers':
        if not verify_seeanswers_access(doc_info, require=False, check_duration=True):
            if verify_view_access(doc_info):
                flash("Did someone give you a wrong link? Showing normal view instead of see answers view.")
                return redirect(f'/view/{item_path}')

    access = verify_view_access(doc_info, require=False, check_duration=True)
    if not access:
        if not logged_in():
            return redirect_to_login()
        else:
            abort(403)

    timdb = get_timdb()

    if get_option(request, 'login', False) and not logged_in():
        return redirect_to_login()

    try:
        view_range = parse_range(request.args.get('b'), request.args.get('e'))
    except (ValueError, TypeError):
        view_range = None
    start_index = max(view_range[0], 0) if view_range else 0

    doc, xs = get_document(doc_info, view_range)

    clear_cache = get_option(request, "nocache", False)
    hide_answers = get_option(request, 'noanswers', False)

    teacher_or_see_answers = route in ('teacher', 'answers')
    current_user = get_current_user_object() if logged_in() else None
    doc_settings = doc.get_settings(current_user)

    if not view_range:
        try:
            preamble_pars = doc.insert_preamble_pars()
        except PreambleException as e:
            flash(e)
        else:
            xs = preamble_pars + xs

    # Preload htmls here to make dereferencing faster
    try:
        DocParagraph.preload_htmls(xs, doc_settings, clear_cache)
    except TimDbException as e:
        log_error(f'Document {doc_id} exception:\n{traceback.format_exc(chain=False)}')
        abort(500, str(e))
    if doc_settings:
        src_doc = doc.get_source_document()
        if src_doc is not None:
            DocParagraph.preload_htmls(src_doc.get_paragraphs(), src_doc.get_settings(), clear_cache)

    rights = doc_info.rights
    word_list = (doc_info.document.get_word_list()
                 if rights['editable'] and current_user and current_user.get_prefs().use_document_word_list
                 else [])
    # We need to deference paragraphs at this point already to get the correct task ids
    xs = dereference_pars(xs, context_doc=doc)
    total_points = None
    tasks_done = None
    task_groups = None
    show_task_info = False
    user_list = []
    task_ids, plugin_count, no_accesses = find_task_ids(xs, check_access=teacher_or_see_answers)
    if teacher_or_see_answers and no_accesses:
        flash('You do not have full access to the following tasks: ' + ', '.join([t.doc_task for t in no_accesses]))
    points_sum_rule = doc_settings.point_sum_rule(default={})
    try:
        total_tasks = len(points_sum_rule['groups'])
    except:
        total_tasks = len(task_ids)
        points_sum_rule = None
    if teacher_or_see_answers:
        user_list = None
        ug = None
        if usergroup is not None:
            ug = UserGroup.get_by_name(usergroup)
            if not ug:

timApp/templates/create_new.html
{% extends "base.html" %}
{% block title %}This page does not yet exist.{% endblock %}
{% block content %}
    <p class="errormsg">{{ message or self.title() }}</p>
    {% if session.user_id %}
        {% if show_create_new %}
            <bootstrap-panel title="Create a new document here">
                <create-item
                        item-type="document"
                        full-path="{{ new_item }}"
                        force="true"
                        {% if forced_template %}
                        template="{{ forced_template }}">
                        {% endif %}
                </create-item>
            </bootstrap-panel>
{#
            <bootstrap-panel title="Create a new folder here">
                <create-item item-type="folder" full-path="{{ new_item }}"></create-item>
            </bootstrap-panel>
#}
        {% else %}
            You cannot create documents or folders here.
        {% endif %}
    {% else %}
        To create a new document or a folder, log in.
    {% endif %}
    {% if found_item %}
        <a href="/view/{{ found_item.path }}">To the first existing item ({{ found_item.title }}) in your search.</a>
    {% else %}
        <a href="{{ url_for('view_page.index_page') }}">To the index.</a>
    {% endif %}
{% endblock %}

timApp/templates/document.html
{% extends 'item.html' %}
{% block head %}
    {{ super() }}
    <script>
        {% if edit_mode %}
        var editMode = {{ edit_mode|tojson }};
        {% else %}
        var editMode = null;
        {% endif %}
    </script>
{% endblock %}

{% block itemlinks %}
    {{ super() }}
    {% if item.rights.teacher %}
         <li role="presentation" {{ active('view_page.teacher_view') }}><a id="headerTeacher" href="/teacher/{{ item.path }}">Teacher</a></li>
    {% endif %}
    {% if item.rights.see_answers %}
         <li role="presentation" {{ active('view_page.see_answers_view') }}><a id="headerAnswers" href="/answers/{{ item.path }}">Answers</a></li>
    {% endif %}
     <li role="presentation" {{ active('view_page.lecture_view') }}><a id="headerLecture" href="/lecture/{{ item.path }}">Lecture</a></li>
     <li role="presentation" {{ active('view_page.velp_view') }}><a id="headerVelp" href="/velp/{{ item.path }}">Velp</a></li>
     <li role="presentation" {{ active('view_page.slide_document') }}><a id="headerSlide" href="/slide/{{ item.path }}">Slide</a></li>
{% endblock %}
{% block languages %}
    {% if translations %}
        {% for tr in translations %}
                <a class="label label-primary" href="/{{ route }}/{{ tr.path }}">{{ tr.lang_id }}</a>
        {% endfor %}
    {% endif %}
{% endblock %}

timApp/templates/dumbo_html_error.html
{% extends "error.html" %}
{% block content %}
<p>
    The markdown server failed to render markdown to HTML. This usually means that the mathematical formulas
    in this document are still being processed. This page will refresh periodically. Please wait.
</p>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        window.location.reload();
    });
</script>
{% endblock %}

timApp/templates/duration_unlock.html
{% extends 'item.html' %}
{% block content %}
    <div class="alert alert-warning">
        <i class="glyphicon glyphicon-warning-sign"></i>
        {% if access.unlockable %}
            You are about to access a time-limited {{ item_type }}.
            After you click Unlock, your access to this {{ item_type }} will be removed in {{ access.duration | timtimedelta }}.
        {% elif access.duration_expired %}
            You cannot unlock this item anymore (deadline expired {{ access.duration_to | timreldatetime }}).
        {% elif access.duration_future %}
            You can unlock this item in {{ access.duration_from | timreldatetime }}.
        {% elif access.expired %}
            Your access to this item has expired {{ access.accessible_to | timreldatetime }}.
        {% elif access.future %}
            You can access this item in {{ access.accessible_from | timreldatetime }}.
        {% else %}
            You don't have access to this item.
        {% endif %}
    </div>
    {% if access.unlockable %}
        <div class="text-center">
            <a href="/view/{{ item.path }}?unlock=true" class="timButton">Unlock</a>
        </div>
    {% endif %}
{% endblock %}

timApp/templates/error.html
{% extends "base.html" %}
{% block title %}{{ code }} {{ status }}{% endblock %}
{% block content %}
    <p class="errormsg">{{ message }}</p>
{% endblock %}

timApp/templates/item.html
{% extends 'base.html' %}
{%- macro active(endpoint) -%}
    {%- if request.endpoint == endpoint -%}
        class="active"
    {%- endif -%}
{%- endmacro -%}
{% block head %}
    {{ super() }}
    <script>
        var item = {{item|tojson}};
        var breadcrumbs = {{item.parents_to_root()|tojson}};
    </script>
{% endblock %}
{% block header %}
    {{ super() }}
    {% if not hide_links %}
        <div class="pull-right">
                    <button ng-cloak
                            ng-if="$ctrl.taggedAsCourse && !$ctrl.bookmarked"
                            ng-click="$ctrl.addToBookmarkFolder()"
                            title="Add this page to 'My courses' bookmark folder"
                            class="timButton label">
                        Add to My courses
                    </button>
                {% block languages %}
                {% endblock %}
        </div>
    <div class="nav nav-tabs">    {% block itemlinks %}
        <li role="presentation" {{ active('view_page.view_document') }}><a id="headerView" href="/view/{{ item.path }}">View</a></li>
        <li role="presentation" {{ active('manage_page.manage') }}><a id="headerManage" href="/manage/{{ item.path }}">Manage</a></li>
    {% endblock %}</div>
        <tim-breadcrumbs ng-cloak>
            <ol ng-init="bc = $parent.$ctrl" class="breadcrumb">
                <li ng-repeat="c in bc.crumbs | orderBy:'-'">
                    <a href="/{{ route or 'view' }}/{{ '{{ c.path | escape }}' }}">{{ '{{ c.title }}' }}</a>
                </li>
                <li class="active">{{ '{{ bc.item.title }}' }}</li>
            </ol>
        </tim-breadcrumbs>
    {% endif %}
{% endblock %}

timApp/templates/lectureInfo.html
{% extends "document.html" %}
{% block title %}Lecture info{% endblock %}
{% block head %}
    {{ super() }}

    <script>
        var lecture = {{lecture|tojson}};
        var inLecture = {{in_lecture|tojson}};
    </script>

{% endblock %}
{% block content %}
<tim-lecture-info></tim-lecture-info>
{% endblock %}

timApp/templates/loginpage.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <p class="text-center">
                {% if not hide_require_text %}
                    Login is required for this document.
                {% endif %}
                Please use the above button to log in.
            </p>
        </div>
    </div>
{% endblock %}

timApp/templates/manage.html
{% extends obj_name + ".html" %}
{% set is_folder = obj_name == 'folder' %}
{% block title %}{{ item.title }} - Manage{% endblock %}
{% block head %}
    {{ super() }}
    <script>
        var accessTypes = {{access_types|tojson}};
        var objName = {{obj_name|capitalize|tojson}};
    </script>
{% endblock %}
{% block content %}
    <tim-manage></tim-manage>
{% endblock %}

timApp/templates/manage_folder.html
{% extends 'manage.html' %}
{% set obj_name = 'folder' %}

timApp/templates/search.html
{% extends 'base.html' %}
{% block title %}Search - {{ query }}{% endblock %}
{% block content %}
    Found{% if too_many %} at least{% endif %} {{ results|length }} result(s).
    <ul>
        {% for result in results %}
            <li><a href="{{ result.document.url_relative }}#{{ result.par.get_id() }}">{{ result.document.title }}</a> ({{ result.document.path }})</li>
        {% endfor %}
    </ul>
{% endblock %}

timApp/templates/settings.html
{% extends "base.html" %}
{% block title %}Settings{% endblock %}
{% block customcss %}
    {# The logic for custom CSS is dynamic on settings page, so we disable it here. #}
{% endblock %}
{% block head %}
    {{ super() }}
    <script>
        var settings = {{ prefs|tojson }};
        var css_files = {{ css_files|tojson }};
        var notifications = {{ notifications|tojson }};
    </script>
{% endblock %}
{% block content %}
    <tim-settings></tim-settings>
{% endblock %}

timApp/templates/show_slide.html
{% extends 'view_html.html' %}
{# The custom style should be the last style element, so don't render it in view_html.html #}
{% block viewhtml_customcss %}{% endblock %}
{% block head %}
    {{ super() }}
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    {% include 'partials/doc_customcss.html' %}
    <script>
        var background_url = {{ (slide_background_url or None)|tojson }};
        var background_color = {{ (slide_background_color or None)|tojson }};
    </script>
{% endblock %}

{% block body %}
    <tim-view>
    <div class="reveal" style="visibility: hidden">
        <div class="slides paragraphs">
            <section>
                {# Because of Jinja2 scoping rules, we need to use a single-element array #}
                {% set prev_is_empty = [True] %}
                {% set sectionchange = '</section><section>'|safe %}
                {% for t in text %}
                    {% if 'settings' in t.attrs %}
                        {# do nothing #}
                    {% elif t.md.startswith('---') and t.md.endswith('---') %}
                        {% if not prev_is_empty[0] %}
                            {{ sectionchange }}
                            {% set _ = prev_is_empty.append(prev_is_empty.pop() or True) %}
                        {% endif %}
                    {% else %}
                        {% if (t.html.startswith("<h1") or
                               t.html.startswith("<h2") or
                               t.html.startswith("<h3")) and not prev_is_empty[0] %}
                            {{ sectionchange }}
                        {% endif %}
                        <div class="{{ t.cls }}"
                             id="{{ t.id }}"
                             t="{{ t.t }}"
                             attrs="{{ t.attrs_str }}">
                            {{ t.html|safe }}
                        </div>
                        {% set _ = prev_is_empty.append(prev_is_empty.pop() and False) %}
                    {% endif %}
                {% endfor %}
            </section>
        </div>
    </div>
    </tim-view>
{% endblock %}